name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3

    - name: Run a simple script
      run: echo "Code was merged to main at $(date) and will be pushed to prod."
